### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by bogdan2011** [gicking/STM8-SPL_SDCC_patch#10]
I managed to patch the library but I get a syntax error when trying to compile the source files in "src":

../inc/stm8s_it.h:45: syntax error: token -> '__interrupt' ; column 12

**Comment by gicking** [comment]
sorry for this late response! Somehow this issue slipped my attention  :-(

Does this issue still exist? If yes, which compiler did you use and can you please provide an example which reproduces the error? Thanks and sorry again!

**Comment by pij-se** [comment]
The issue still exists but is not related to this patch. The firmware source AN4101 for STM8A-DISCOVERY ([STSW-STM8073](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm8-embedded-software/stsw-stm8073.html)) and possibly others includes `stm8s_it.h` which declares function prototypes in the following format:

`INTERRUPT void TRAP_IRQHandler(void); /* TRAP */`

`stm8s.h` defines `INTERRUPT` as the keyword `__interrupt`. SDCC, does not seem to allow `__interrupt` to precede the declaration; the solution appears to be having `INTERRUPT` follow the declaration instead:

`void TRAP_IRQHandler(void) INTERRUPT; /* TRAP */`

**Comment by gicking** [comment]
understood. Unfortunately that is something I cannot patch. Specifically as you already noted, SDCC requires the "__interrupt" keyword after the function name. In all examples provided with SPL I already fixed that, but of course this is still present in any firmware you download independently. 

Luckily there is a simple fix to **this** problem: as "stm8s_it.h" is not project specific, just replace it a patched one from the SPL examples, e.g. "Project/STM8S_StdPeriph_Examples/EXTI/EXTI_InterruptPriority/stm8s_it.h". Same of course also applies for STM8AL.

But apart from this very simple fix, there are other issues with the mentioned AN4101 firmware and SDCC. Most of which are easy to fix, e.g. missing type declarations u16 etc., or adding #include "stm8s_it.h" to main.c (mandatory for SDCC interrupts). But some, like RAM functions or EEPROM variables in "discover_functions.c" (STM8AL_Discover) would require more effort to fix. 

Attached please find a quick fix which at least compiles under SDCC v4.1.0 and Linux. However, it is likely not fully functional due to the above RAM functions or EEPROM variables, which I didn't fix. Hope this helps you...!?

[AN4101_patched.tar.gz](https://github.com/gicking/STM8-SPL_SDCC_patch/files/6719854/AN4101_patched.tar.gz)

**Comment by gicking** [comment]
I assume this topic is closed...!? If not, please re-open it
