### ISSUE TITLE
Interrupt table warnings sdcc v4.4.2 build

### ISSUE THREAD

**Issue by LightningStalker** [gicking/STM8-SPL_SDCC_patch#14]
Using latest sdcc build:
```
../stm8l15x_it.h:#: warning 283: function declarator with no prototype
...
../stm8l15x_it.c:#: warning 283: function declarator with no prototype
```
warning but compile successfully

**Comment by gicking** [comment]
thanks for pointing this out! Apparently there was a change in SDCC some time ago, resulting in stricter warning (see e.g. https://sourceforge.net/p/sdcc/support-requests/169/)

Luckily the fix is straightforward: just change `void a()` to `void a(void)` for `INTERRUPT_HANDLER` and `INTERRUPT_HANDLER_TRAP` in the device header file.

I have fixed this now in my patches. Thanks again and have a great day  :-)

**Comment by LightningStalker** [comment]
No more ugly warning!
